name: 'Run Shell Tests'
description: 'Runs the shell-based test suite for path_helper'

inputs:
  ruby-version:
    description: 'Ruby version being tested (for reporting)'
    required: true

outputs:
  test-result:
    description: 'Test result (passed/failed)'
    value: ${{ steps.run-tests.outcome }}

runs:
  using: 'composite'
  steps:
    - name: Run tests
      id: run-tests
      shell: bash
      run: |
        set -o pipefail
        /tmp/spec/shell_spec.sh | tee test_output.log

    - name: Display test failures
      if: failure()
      shell: bash
      run: |
        echo "========================================"
        echo "TEST FAILURES - Ruby ${{ inputs.ruby-version }}"
        echo "========================================"
        if [ -f test_output.log ]; then
          echo ""
          echo "Failed tests:"
          grep -A 50 "Failure" test_output.log || cat test_output.log
          echo ""
          echo "========================================"
        fi

    - name: Generate test summary
      if: always()
      shell: bash
      run: |
        echo "## Test Results for Ruby ${{ inputs.ruby-version }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -f test_output.log ]; then
          if grep -q "Passed!" test_output.log; then
            echo ":white_check_mark: **All tests passed**" >> $GITHUB_STEP_SUMMARY
          else
            echo ":x: **Tests failed**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Output" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            cat test_output.log >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo ":warning: **No test output found**" >> $GITHUB_STEP_SUMMARY
        fi
